### ISSUE TITLE
Files permissions not working into the forge version

### ISSUE THREAD

**Issue by mvisonneau** [puppetlabs-operations/puppet-puppetlabs_apt#7]
I'm having trouble using the packaged version of the module. The files permissions are not correct and throw an access error while applying the manifest.
I do not have the problem with the current commit of the repo though.

Solved it doing a `chmod -R +r /etc/puppet/modules/puppetlabs_apt`

Would it be possible to recompile the module on the forge then ?

**Comment by xaque208** [comment]
Sure, we can cut a new release.

**Comment by xaque208** [comment]
0.0.5 has been released.  Re-open if you still have troubles.

**Comment by mvisonneau** [comment]
Great, problem solved thank you :)
